#!/usr/bin/python3
# © 2022 Kaito Suzuki
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
  try:
      return int(s)
  except:
      return float(s)

ans = 0

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

if ans % 2 == 0:
    guki = ('偶数')
else:
    guki = ('奇数')
print(guki)
print(ans)
